# Generated by Django 5.0.3 on 2024-05-23 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursegroup',
            name='lang',
            field=models.CharField(default="O'zbek", max_length=50),
        ),
    ]
