# Generated by Django 5.0.3 on 2024-05-23 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_coursegroup_lang'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcontent',
            name='student_id',
        ),
    ]
