# Generated by Django 5.0.3 on 2024-05-23 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0003_remove_groupcontent_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.coursegroup'),
        ),
    ]
