# Generated by Django 5.0.3 on 2024-05-23 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0004_alter_groupmember_group_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcontent',
            name='description',
            field=models.TextField(default='hello'),
            preserve_default=False,
        ),
    ]
