# Generated by Django 5.0.3 on 2024-05-28 08:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('management', '0006_alter_groupcontent_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupcontent',
            name='group_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.coursegroup'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('condition', models.CharField(blank=True, choices=[('HA', 'Ha'), ('YOQ', "Yo'q")], max_length=3, null=True)),
                ('group_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group')),
                ('group_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.groupmember')),
            ],
        ),
    ]
