# Generated by Django 5.0.3 on 2024-05-28 08:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0007_alter_groupcontent_group_id_attendance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='group_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.coursegroup'),
        ),
    ]
