# Generated by Django 5.0.3 on 2024-05-29 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0008_alter_attendance_group_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='condition',
            field=models.CharField(blank=True, choices=[('', ''), ('HA', 'Ha'), ('YOQ', "Yo'q")], max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='date',
            field=models.DateField(),
        ),
    ]
