# Generated by Django 5.0.3 on 2024-05-30 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0010_alter_course_name_alter_coursegroup_lang_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='condition',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Ha'), ('2', "Yo'q")], max_length=3, null=True),
        ),
    ]
