# Generated by Django 5.0.3 on 2024-06-03 09:59

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0011_alter_attendance_condition'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupcontent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
