# Generated by Django 5.0.3 on 2024-06-04 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0012_groupcontent_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupmember',
            name='permission',
            field=models.CharField(blank=True, choices=[('', ''), ('1', 'Ruxsat'), ('2', 'Zapret')], max_length=1, null=True),
        ),
    ]
