# Generated by Django 5.0.3 on 2024-06-04 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0013_alter_groupmember_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyinfo',
            name='end_day',
            field=models.CharField(blank=True, choices=[('DU', 'Dushanba'), ('SE', 'Seshanba'), ('CHOR', 'Chorshanba'), ('PAY', 'Payshanba'), ('JU', 'Juma'), ('SHAN', 'Shanba'), ('YAK', 'Yakshanba')], max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='companyinfo',
            name='start_day',
            field=models.CharField(blank=True, choices=[('DU', 'Dushanba'), ('SE', 'Seshanba'), ('CHOR', 'Chorshanba'), ('PAY', 'Payshanba'), ('JU', 'Juma'), ('SHAN', 'Shanba'), ('YAK', 'Yakshanba')], max_length=4, null=True),
        ),
        migrations.DeleteModel(
            name='Day',
        ),
    ]
