# Generated by Django 5.0.3 on 2024-06-04 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0014_alter_companyinfo_end_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='files')),
                ('description', models.TextField(blank=True, null=True)),
                ('group_member_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.groupmember')),
            ],
        ),
    ]
