# Generated by Django 5.0.3 on 2024-05-30 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='gender',
            field=models.CharField(choices=[('', ''), ('Erkak', 'Erkak'), ('Ayol', 'Ayol')], max_length=5),
        ),
    ]
