# Generated by Django 5.0.3 on 2024-05-30 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_profile_gender'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
